[package]
name = "nasadem"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "*"
geo-types = "*"

[dev-dependencies]
bincode = "*"
hextree = { version = "*", features = ["serde-support"] }

[profile.release]
debug = true
